### ISSUE TITLE
Type hinting custom data classes

### ISSUE THREAD

**Issue by btcookies** [Badger-Finance/badger-rewards#139]
There are spots in our code where we pass a boost or multiplier or tree object (or part of one) and we aren't typing it. We should create data classes that describe these objects so users have a better idea of what an object should look like when being used in or passed into a funciton.

**Comment by btcookies** [comment]
rewards_to_merkle_tree
to_merkle_format
bcvx_claims_snapshot
bcvxcrv_claims_snapshot
distribute_rewards_to_snapshot
get_sett_multipliers
get_user_multipliers
boost_sett
calc_sushi_distribution
convert_to_merkle_tree
propose_root
manage_root
get_claimable_for
get_claimed_for
fetch_tree
fetch_current_tree
fetch_pending_tree
fetch_current_merkle_data
fetch_pending_merkle_data
fetch_all_schedules
generate_rewards_in_range
fetch_block_by_timestamp
token_diff_table
combine_rewards
get_last_proposed_cycle
calc_next_cycle_range

**Comment by SHAKOTN** [comment]
Closing this now, as PR was merged and new issues for futher work are created
