### ISSUE TITLE
Address 0x782A2B258568A85ee429e845E0770d7a4130280C showing 0 boost

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/badger-rewards#189]
Address `0x782A2B258568A85ee429e845E0770d7a4130280C` is showing no boost while they are in multiple vaults on arbitrum, but none on ethereum.

REFERENCE: https://api.badger.finance/v2/accounts/0x782A2B258568A85ee429e845E0770d7a4130280C?chain=arbitrum

The API is picking up balances, but the boost file seems to have nothing for them:
![image](https://user-images.githubusercontent.com/6303774/139518119-403461ce-d2e8-4cc6-a8e8-08a82d7013a3.png)

**Comment by Darruma** [comment]
Similar issue with address 0x72eA986B93b63bc0e0d146b850003C2e6FF187aC

Showing 0 boost on the api but in the badger-boosts file the data is correct

```js
 "0x72ea986b93b63bc0e0d146b850003c2e6ff187ac": {
            "boost": 10,
            "nativeBalance": 1542.85,
            "nonNativeBalance": 247171.27684376235,
            "stakeRatio": 0.006242027875169491,
            "multipliers": {
                "0x4591890225394BF66044347653e112621AF7DDeb": 0.009441503440203223,
                "0x60129B2b762952Dfe8b21f40ee8aa3B2A4623546": 0.008064937144835662,
                "0xBA418CDdd91111F5c1D1Ac2777Fa8CEa28D71843": 0.019204000340631987,
                "0xFc13209cAfE8fb3bb5fbD929eC9F11a39e8Ac041": 0.025372154162070584
            }
        },

**Comment by mitche50** [comment]
Fixed - api issue
