### ISSUE TITLE
Add delay to cycle propose

### ISSUE THREAD

**Issue by btcookies** [Badger-Finance/badger-rewards#209]
Added sleep to cycle approve seems to have fixed the `Transaction with hash: '0x644f8714385cfcaa6b36e55819bf912f2972e20cdd421fae9ef7f03de369daf8' not found.` issue causing failed cycles. This error still occurs on propose and causes noise in the channel, would like to add the sleep or otherwise remediate the issue so it doesn't occur on propose.

**Comment by mitche50** [comment]
I think this was resolved with our wrapper addition on await transaction receipt.  Please confirm and close this if no longer relevant

**Comment by btcookies** [comment]
Confirmed, closing.
