### ISSUE TITLE
Prepare for bveCVX emissions via treedistribution and emission schedules

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-rewards#210]
At the end of this week, the techops multisig will execute a 24 hour tree distribution to emit some bveCVX bought from bribe money to holders of bveCVX.

Starting early next week.  All convex setts will start emitting bveCVX via tree distributions.

Things to confirm:

1:  bveCVX will be handled by emisisons and UI when distributed both via emissions schedules and treedistribution events.
2; all emissions to the bveCVX in the bveCVX LP are blacklisted

**Comment by mitche50** [comment]
Confirmed - Tree distribution events are auto indexed and the new strategies have been added to the subgraph.  emissions schedules are confirmed as working as we're using them to distribute the bveCVX afrom the SPELL sale.
