### ISSUE TITLE
Distribute 100% of rewards via tree for native LP setts

### ISSUE THREAD

**Issue by btcookies** [Badger-Finance/badger-rewards#229]
Right now we're auto-compounding 50% of the weekly emissions into the LP setts and distributing 50% of weekly emissions via the tree. Per council vote [here](https://discord.com/channels/743271185751474307/842854176488161311/901124337032114217) we want to move to distributing 100% of emissions for the LP setts (digg/wbtc SLP, badger/wbtc SLP, badger/wbtc uni LP) via the tree.

**Comment by mitche50** [comment]
no code change required here - to submit in badger-ape
