### ISSUE TITLE
Emissions should use time weighted averages to distribute rewards

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/badger-rewards#243]
Currently emissions are done using a snapshot model that doesn't take into account the prior holdings of addresses.  We need to update this model to include time weighted average from the prior tree distribution event to appropriately assign rewards

**Comment by mitche50** [comment]
https://hackmd.io/@utbskePYTLmslPtU8zjZQQ/BktRYh5ut

Requirements documentation

**Comment by SHAKOTN** [comment]
#450
