### ISSUE TITLE
Separate staging logging from prod logging - boost

### ISSUE THREAD

**Issue by btcookies** [Badger-Finance/badger-rewards#254]
Staging boost bots currently writing to the [chain]-boost-bot channels in Discord. Should instead write to test-[chain]-boost channels.

- set up webhooks in test-[chain]-boost channels
- create secrets in aws secrets manager
- update iam policy with new secret arns
- update monitoring secret names for staging

**Comment by mitche50** [comment]
@btcookies is this complete?
