### ISSUE TITLE
Fix bcvx_claims_snapshot and bcvxcrv_claims_snapshot

### ISSUE THREAD

**Issue by SHAKOTN** [Badger-Finance/badger-rewards#280]
Both bcvx_claims_snapshot and bcvxcrv_claims_snapshot methods are broken, since they are calling `claims_snapshot()[BCVXCRV]` without `chain` parameter.

**Comment by Darruma** [comment]
This will be fixed with the `split-boost` branch - We are going to refactor the code to allow for custom behaviours for certain addresses

**Comment by mitche50** [comment]
closed via #281
