### ISSUE TITLE
API / HTTP Request Improvement

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/badger-rewards#288]
API / HTTP requests should be handled through a function which catches any non-200 responses and retries with maximum amount of retries.  If retries are exhausted, log to discord and gracefully exit.

_Originally posted by @mitche50 in https://github.com/Badger-Finance/badger-rewards/pull/285#r748323431_

**Comment by mitche50** [comment]
https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/

**Comment by SHAKOTN** [comment]
https://github.com/Badger-Finance/badger-rewards/issues/289

**Comment by btcookies** [comment]
https://github.com/Badger-Finance/badger-rewards/issues/298

**Comment by btcookies** [comment]
`badger_api/requests.py`

**Comment by SHAKOTN** [comment]
On this issue now
