### ISSUE TITLE
Async HTTP Transport in subgraph utils

### ISSUE THREAD

**Issue by SHAKOTN** [Badger-Finance/badger-rewards#372]
Noticed that we are using async HTTP transport in gql utils:
```
def make_gql_client(name):
    url = subgraph_url(name)
    transport = AIOHTTPTransport(url=url)
```
While this is not critical, I suggest that we don't mix sync with async in Python. What do you think @mitche50 @btcookies @Darruma ?

**Comment by Darruma** [comment]
Originally the idea was to make this data fetching async, instead we can replace AIOHTTPTransport with RequestsHTTPTransport in when creating the grapgql client

**Comment by SHAKOTN** [comment]
> riginally the idea was to make this data fetching async, instead we can replace AIOHTTPTransport with RequestsHTTPTransport in when creating the grapgql client

Agreed. I will do it then. Thanks for answering!
