### ISSUE TITLE
Clean scripts/ module

### ISSUE THREAD

**Issue by SHAKOTN** [Badger-Finance/badger-rewards#410]
data/
scoring/
check_claimable.py

Look unused and can be removed

Save the knowledge into some md file with snippets

**Comment by mitche50** [comment]
Additional files / directories that can be removed:
`eth/retroactive/`
Any file prefaced with `manual_` can be removed
`eth/custom_propose_eth.py`
`fix_checksum/`
`fix_cycle/`
