### ISSUE TITLE
Redirect ibBTC rewards to the ibBTC multisig

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-rewards#462]
Including past and current rewards.  Badger is still blacklisted.

0xB76782B51BFf9C27bA69C77027e20Abd92Bcf3a8 is the ibBTC mutlisig as per https://github.com/Badger-Finance/badger-ape/issues/874

**Comment by mitche50** [comment]
https://github.com/Badger-Finance/badger-rewards/commit/db2c8e61064679629461f0921b187fa14bdee481

Custom rewards behavior handles if a destination address is in this list, with a provided function.  In this case, the rewards are redirected to the ibBTC multisig

This is prioritized behind the pending unclaimed rewards upgrade #422
