### ISSUE TITLE
Enhancement: Add BADGER in the Across Pool to boost balance

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/badger-rewards#518]
Across has a BADGER pool that allows users to quickly bridge BADGER from Arbitrum to ETH.  This pool is getting 39.1975% projected APY per the below image.

To help promote usage of the pool, and thus arbitrage opportunities to keep ARB and ETH more in line, we can add in BADGER that's deposited to the across pool to be considered to Badger Boost.  This should be implemented identically to the fBADGER rari implementation.

Technical Details:
- contract address: 0x43298f9f91a4545df64748e78a2c777c580573d6
- Network: ETH
- TBD how to determine underlying value

**Comment by mitche50** [comment]
Calculation to determine value: `(liquidReserves() + utilizedReserves() - undistributedLpFees()) / totalSupply * balanceOf(user)`

**Comment by Darruma** [comment]
We can track balanceOf(user) on a subgraph using the LiquidityAdded and LiquidityRemoved events on the BridgePoolPod contract. We can then use the formula above to determine how much badger we can add to each user

**Comment by mitche50** [comment]
closed by #600
