### ISSUE TITLE
Migrate Old Strategy Rewards

### ISSUE THREAD

**Issue by Darruma** [Badger-Finance/badger-rewards#554]
https://github.com/Badger-Finance/badger-ape/issues/711

There will need to be a script to allocate rewards to users at the point of migration
We will need to add a special case to the tree distribution query so the rewards don't get distributed by the cycle bots

**Comment by mitche50** [comment]
Planned to implement Monday, 1/31 at 9am EST.  Will communicate planned downtime of cycles for 6 hours (9am -> 2pm EST)
