### ISSUE TITLE
redirect emissions that should be going to crvbvecvxcvxf pool to bcrvbvecvxcvxf holders

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-rewards#593]
emissions that should be going to bvecvxcvxf pool (but arent since the pool contract cant claim and therefore we blacklisted it) should be going the bbvecvxcvxf vault token holders instead.

**Comment by Tritium-VLK** [comment]
**Story:**  As a user, I would like to receive my share of bveCVX emissions for my bveCVX/CVX LP tokens deposited in either the badger sett or Rari.   Receiving my share of locked convex rewards would provide me a more interesting emissions profile, and would ensure that I continue to receive good yields on my locked CVX even as the LP pool scales in volume.

**Greater User Context:**  
As CVX HODLer I am very excited about the ability to have a decently liquidity vlCVX that yields competitively and offers some utility.  The ability to borrow from it it my holy grain.  BadgerDAO has tweeted a roadmap around this holy grail that has me very excited and watching closely. https://twitter.com/BadgerDAO/status/1488920416085323778.  As long as this rari thing starts to exist in the next weeks, and I don't end up with crap yields on my bveCVX LP when everyone deposits into it and the badger only emissions are diluted, I will be super impressed with Badger.   Managing to maintain decent liquidity depth and competitive yields over a few months would make it very difficult for me to not deposit quite a bit of my CVX in this thing.


**Scope of this ticket:**

The bveCVX/CVX LP pool HODLs a bunch of bveCVX that should receive emissions of BADGER, bveCVX and bcvxCRV.  It is currently blacklisted.

In order for the pool to scale, it is required that the rewards earned by bveCVX in the LP pool is distributors to stakers in the badger bveCVX LP sett, or HODLers of the rari bveCVX LP deposit token.

The balance bveCVX is quite dynamic, so assuming a 50% ratio is not sufficient.  Over the last months the pool spent a lot of time with 70-80% bveCVX in it.  As such, the emissions redirection must be sensitive to the makeup of the curve pool and/or not take more or less emissions from bveCVX than the LP holdings are entitled too.  

**Timing/Deadline**
Based on recent comms and as part of our general efforts to build a "we're winning" narrative around ibBTC and bveCVX, there is some expectation of borrowing towards the end of February.  While this ticket is not dependant on borrowing, we have decided that borrowing will only be on bvecvx/cvx LP tokens.   

This means that if our borrowing program is successful, the supply of bveCVX/CVX LP will go up pretty quickly, and before long it will be yielding poorly in a way that can not be explained to depositors.  This will be a difficult time, and will likely take quite a lot of wind out of our sails.

For that reason, it would be really nice if this could be done before mid march (4ish weeks after rari opens up  for bvecvx which should be in in the next week or two.)

**For context:**
There is also #592 to include the rari LP tokens in rewards (this can/should be done first and can work with the currently emitted badger)
There is also this ticket: https://github.com/Badger-Finance/badger-multisig/issues/101 to add more Dollar coins to Rari so a number of team-members can go round up more deposits.

Contact Tritium for the ticket to actually add bveCVX LP to rari (i'll try to remeber to drop the ftoken address in).

**Comment by mitche50** [comment]
TODO:
- [ ] Create function to determine bveCVX balance of bveCVX/CVX curve LP
- [ ] Use this ratio to determine the amount of bveCVX in user's bveCVX/CVX curve LP deposited in the vault
- [ ] Set up custom redirect to handle emissions redirection from bveCVX/CVX curve LP vault -> holders based on the current composition of the LP
- [ ] Include rari holdings

**Comment by mitche50** [comment]
Delayed for marketing to next sprint
