### ISSUE TITLE
Separate boost and rewards file writes

### ISSUE THREAD

**Issue by btcookies** [Badger-Finance/badger-rewards#61]
The boost bot and cycle bots all write to the same s3 file, which is then read by the api and reported out to users. This may be causing some weird race conditions when bots write at the same time / overwrite each other / write in specific orders.

Might be causing issue where boost range % isn't shown underneath setts? Need to research.

Ticket is for researching creating separate files, one that boost bot writes to and one that cycle bots write to. Would require refactoring the api. The goal of this is to decouple boost and rewards so they can't be overwritten by one another.

**Comment by btcookies** [comment]
Also might be issue with faster cycles, ran into invalid cycle / weird apy issues when running every 10 min. Jintao says ui / api caches the s3 file 8 min at a time.

**Comment by mitche50** [comment]
Still relevant:
- Will only be an issue if approve and boost run at the same time.

**Comment by mitche50** [comment]
Closed by #360
