### ISSUE TITLE
Send 3012.47478801767 bveCVX to the treasury-ops multisig

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-rewards#613]
this bveCVX is a fee for yield redirection that was sent to the tree instead of the multisig.  It can be paid out whenever, but the sooner the better so the multi can earn yields on it's bveCVX.

See this sheet for details:
https://docs.google.com/spreadsheets/d/1R3dBig3f13jNgjTuNhLXcGVle1gxERNNKJD-2TAWgbE/edit#gid=1065480511

The allocated tokens come out of the bveCVX paid into the tree under this TX:
https://etherscan.io/tx/0x0caeb598f6dba35e7d21f3f41fb7bc820d7f197012db9f04701f43dbed9c4c98

**Comment by mitche50** [comment]
Custom cycle for:
3012474788017670000000 (3012.47478801767) bveCVX to be distributed to address `0x042B32Ac6b453485e357938bdC38e0340d4b9276` (treasuryops.badgerdao.eth)

**Comment by mitche50** [comment]
closed by #624
