### ISSUE TITLE
Unclaimed balances in boost

### ISSUE THREAD

**Issue by Darruma** [Badger-Finance/badger-rewards#73]
Currently, the tree rewards that haven't been claimed yet don't count towards boost calculations. There are a number of tokens that can affect this

Across chains:
- Badger (Native)
- Digg (Native)

On eth:
- bCvx (Non Native)
- bCvxCrv (Non Native)

We can add these tokens to the boost calculation using the badger api. This will need to be paginated to load in all of the claimable balances for all the current users

**Comment by mitche50** [comment]
This should also encompass including unclaimed balances in rewards generation
