### ISSUE TITLE
Count 80BADGER/20WBTC as Native for boost

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-rewards#909]
Vault: https://etherscan.io/address/0x63ad745506BD6a3E57F764409A47ed004BEc40b1
Strategy: https://etherscan.io/address/0xe43857fE16D18b6633A663389934d6c64D5E81FD 

80% of this balancer pool token is represented by BADGER and should be counted towards native boost.

**Comment by Tritium-VLK** [comment]
Just like curve wbtc/badger and sushi wbtc/badger and uni wbtc/badger.  Badger in staked LP paying fees counts towards boosties.

**Comment by mitche50** [comment]
Now counts as native
